version: '2'
networks:
  backend:

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
  php:
    image: php:7-fpm
    expose:
      - "9000"
    volumes:
      - ./:/var/www/silex
    networks:
      backend:
        aliases:
          - php
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./docker/nginx/silex.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    networks:
      backend: